### ISSUE TITLE
Windows-built of felix

### ISSUE THREAD

**Issue by RudoRoemer** [RudoRoemer/Felix#113]
I had a first go at a windows-built of felix.

For a free FORTRAN90+ compiler, I found Min-GW which seems to work nicely, However, I saw little evidence that it could work with MPI. Rather, a quick Google-search revealed problems. There seems to exist an MPI imlementaion MSMPI, but not sure how to make this work.

Intels fortran compiler can be installed (at a price), but a 30day trial version ought to tell us if it works. I downloaded the installer "parallel_studio_xe_2015_..." but had no success in installing on my local laptop here since the data connection to China seems very slow. I suggest we do this from the UK. Also, if we need to buy this, then I think we have until the end of this month (i.e. this week), so perhaps someone can try quickly?

**Comment by AJMHubert** [comment]
Cheers Rudo, Yes I have been having similar problems with MS-MPI, in fact it won't even install on my windows 10 laptop. I have found just now a quick guide on using MinGW (64 bit) with MSMPI, which may help: http://www.symscape.com/configure-msmpi-for-mingw-w64. Although I think they compile the program in Linux with the MinGw cross-compiler. I'm not sure if this means the executable will run on windows? No time constraint here though, I can play around on my holiday next week

I will try the Intel compiler today to see if I can make any progress.

**Comment by AJMHubert** [comment]
I am having a look at the parallel studio 2016 xe, there is a choice between Cluster, professional,composer for c++ or Fortran (or a combination of the two) .
 https://software.intel.com/en-us/intel-parallel-studio-xe/try-buy

Which one should I use? Is there a reason why we should use the 2015 version?

I'm worried the free trial will only apply to one of the download options.

**Comment by RudoRoemer** [comment]
No reason for 2015, use 2016.

I did not look hard, but thought that “professional” sounded best. We do not need a big package here, just something that will allows us to compile on a single machine with multi-cores using MPI. So “cluster” seemed a bit over the top while composer to me looked a bit to unprofessional (but I did not check in detail).

With my best regards,
--
Rudolf A. Roemer
Department of Physics, University of Warwick, Coventry, CV4 7AL, UK www.warwick.ac.uk/go/rudoroemer<http://www.warwick.ac.uk/go/rudoroemer>, Office: +44 2476 5 74328, Mobile: +44 7984 353749

**Comment by RudoRoemer** [comment]
And clearly only fortran (?)

With my best regards,
--
Rudolf A. Roemer
Department of Physics, University of Warwick, Coventry, CV4 7AL, UK www.warwick.ac.uk/go/rudoroemer<http://www.warwick.ac.uk/go/rudoroemer>, Office: +44 2476 5 74328, Mobile: +44 7984 353749

**Comment by AJMHubert** [comment]
Okay, I have managed to compile felix up to the linking stage using the intel compiler. To do so I had to run a specific batch script for both the MPI and ifort implementations under the intel64 bit folder - this set up all the environmental variables and paths required. 

Unfortunately I haven't been able to link the object files yet. I get the error message #11018: cannot open gmodules.o . This happens for every object file. I'm searching for why.

**Comment by AJMHubert** [comment]
wait fixed it, turns out in windows it is .obj instead of .o

Cool, nearly done. I haven't put much effort in linking to the intel mkl in the makefile - the errors are now all about fftw and Lapack linking. 

Hopefully the last hurdle!

**Comment by AJMHubert** [comment]
Right, I have managed to produce a felixsim executable on windows with the Intel compiler. To do so I had to play around with a makefile until something worked - I will upload the makefile to github along with instructions on how to compile on windows. 

Unfortunately the output is weird and looks nothing like a LACBED pattern (in fact there is hardly anything there) - perhaps expected as there are many differences between the windows world and linux world. I also have no idea what I'm doing in the windows world - it was just through trial and error I managed to compile and run felix on windows.

What is the situation with the grant Rudo? 

I will try to get a MinGW build next week during my holiday, I am sure it will be much more challenging!

**Comment by rbeanland** [comment]
Hi Alex,
The grant expires at the end of the month and there is no spend allowed after the end of the month (in practice, we have already passed this point unless you can get an Opera order through before close of play today, I will have to approve it as well as Physics admin).  I think we could squeeze one last bit on consumables if it is not too much, although spend in the last month may not be approved...

Richard

On 28 Aug 2015, at 16:30, Alex Hubert <notifications@github.com<mailto:notifications@github.com>> wrote:


Right, I have managed to produce a felixsim executable on windows with the Intel compiler. To do so I had to play around with a makefile until something worked - I will upload the makefile to github along with instructions on how to compile on windows.

Unfortunately the output is weird and looks nothing like a LACBED pattern (in fact there is hardly anything there) - perhaps expected as there are many differences between the windows world and linux world. I also have no idea what I'm doing in the windows world - it was just through trial and error I managed to compile and run felix on windows.

What is the situation with the grant Rudo?

I will try to get a MinGW build next week during my holiday, I am sure it will be much more challenging!

-
