### ISSUE TITLE
closing all branches

### ISSUE THREAD

**Issue by RudoRoemer** [RudoRoemer/Felix#124]
With the code now re-merged into just a single MASTER branch, we would like to close all old/existing branches. I can easily do it, but are there any branches that should be kept because they contain code that might be useful again later? Perhaps the ARCHER branch?

Once this has been done, I will make a new milestone and alpha-release.

Please let me know asap!

**Comment by AJMHubert** [comment]
By close, would that involve permanently deleting the branches history? 

The branches I can think of that might be useful in the future are:

- FelixGUI
- GUI_image_preview
- Windows_Intel_preview*

If I remember correctly the ARCHER branch doesn't contain anything specific to ARCHER, it was just the version of felix Keith was working on when he was running refinements for Calcium Manganate. I think he just happened to have been using ARCHER for it. I'm sure he will correct me if I am wrong!

The Felix GUI will be of use to me in the future (GUI_image_preview is an add-on to the GUI).

*Probably redundant, only useful if we ever want to use Felix on a windows machine (I think I got it to compile but not run properly)

Cheers,

Alex

**Comment by RudoRoemer** [comment]
I have now deleted "merged" branches. It seems this is permanent, i.e. I do no longer see them in github.

**Comment by RudoRoemer** [comment]
I have just "protected" the 3 branches that Alex lists above, i.e.

    -FelixGUI
    -GUI_image_preview
    -Windows_Intel_preview

That will make deleting them impossible unless the protection is lifted.

**Comment by RudoRoemer** [comment]
I have started deleting old branches. If you want some reopened, pls let me know.
