### ISSUE TITLE
Issues running felixrefine

### ISSUE THREAD

**Issue by JacobJoseph-gu** [RudoRoemer/Felix#131]
It may be a problem on my end, but after compiling the up-to-date felixrefine, it does not seem to run on any of the samples. Old felixrefine used to work on FR-GaAs but I see that it now says on the master branch that it is broken for that sample

**Comment by rbeanland** [comment]
This problem may be because the input file has changed as different refinement methods have been tested.  I have updated felix.inp in the FR-GaAs to the current version and merged the latest code into master, so this should work.  
A second possibility is a recent CSC rebuild which removed old mpi modules.  To build or run the software the command: module load ompi/2.0.1/gnu/4.9.2 :should be run first. (This needs to be amended in the make file but I haven't yet done so.)

**Comment by JacobJoseph-gu** [comment]
Thanks. I have just updated my repository to master.
The felixrefine output was the following:

 --------------------------------------------------------------
 felixrefine: Version: master / BUILD / Alpha                   
              Date: 12-01-2017                                  
              Status: Parabolic refinement test&debug           
     on rank=            0  of            2  in total.
 --------------------------------------------------------------
 D:Refining Isotropic Debye Waller Factors
 Refining by Parabola
 Refining atoms  1  2
 ReadExperimentalImages(           0 )error reading -5-5-3.img, line            1
 ReadExperimentalImages(           1 )error reading -5-5-3.img, line            1
 felixrefine(           1 ) error in ReadExperimentalImages
 felixrefine(           0 ) error in ReadExperimentalImages
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL

I've successfully done apt-get install environment-modules but am having problems using the commands. I will keep working on that so i can use the module load command you suggested.

**Comment by rbeanland** [comment]
This error says that the experimental images are missing.Their names need to be changed to match the expected format. I will try to do this later today

**Comment by rbeanland** [comment]
Ok, done & updated in master.  I haven't tested it, but it should work (famous last words)...

**Comment by JacobJoseph-gu** [comment]
There may be a mistake on my end but with the updates, my output was the following:

 --------------------------------------------------------------
 felixrefine: Version: master / BUILD / Alpha                   
              Date: 12-01-2017                                  
              Status: Parabolic refinement test&debug           
     on rank=            0  of            1  in total.
 --------------------------------------------------------------
 D:Refining Isotropic Debye Waller Factors
 Refining by Parabola
 Refining atoms  1  2
 ReadExperimentalImages(           0 )error reading -5-5-3.img, line            1
 felixrefine(           0 ) error in ReadExperimentalImages
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL

**Comment by rbeanland** [comment]
The renamed files were not being tracked in git.  I've added them now, so there should be a load of *.img files in your FR-GaAs folder when you update.

**Comment by JacobJoseph-gu** [comment]
Thanks Richard, that now works. I have also ran convert on lots of the output images and they look good. Closing Issue
