### ISSUE TITLE
Felix not compiling

### ISSUE THREAD

**Issue by JacobJoseph-gu** [RudoRoemer/Felix#132]
After the latest commit "Merge branch 'multipole'", I get the following error when compiling:

jacob@jacob-VirtualBox:~/Felix/src$ make all
Compiling on Ubuntu, Linux
mpif90 -ffree-line-length-none -fbounds-check -fno-range-check -fimplicit-none  -fcray-pointer -fexternal-blas -DF90 -c smodules.f90 -I/usr/share/doc -llapack -lblas -lfftw3
smodules.f90:73:48:

   CHARACTER*2 :: SElementSymbolMatrix(INElements)!N.B. Number must equal INElements
                                                1
Error: Symbol ‘inelements’ at (1) has no IMPLICIT type
smodules.f90:73:49:

   CHARACTER*2 :: SElementSymbolMatrix(INElements)!N.B. Number must equal INElements
                                                 1
Error: The module or main program array ‘selementsymbolmatrix’ at (1) must have constant shape
smodules.f90:74:6:

   DATA SElementSymbolMatrix/"H", "He", "Li", "Be", " B", " C", " N", "O", "F", "Ne", &
      1
Error: Nonconstant array section at (1) in DATA statement
Makefile:248: recipe for target 'smodules.o' failed
make: *** [smodules.o] Error 1

**Comment by JacobJoseph-gu** [comment]
#133 should resolve this

**Comment by rbeanland** [comment]
Apologies, this comes from my expansion of the periodic table to add 'pseudoatoms'. Initially I let the number of elements vary with a 'use' statement, but I suspect it is not a good idea for one module to rely on another. I replaced it with a fixed number but haven't committed changes for a while.

**Comment by JacobJoseph-gu** [comment]
Thanks, Your commit 920316ecd698a3ee25539949e98f214bb9368a64 does resolve this
