### ISSUE TITLE
Reduce number of beams in felix.inp GaAs

### ISSUE THREAD

**Issue by JacobJoseph-gu** [RudoRoemer/Felix#137]
The increased number of beams added in 94f18c1 significantly increases run time on my machine by an order of magnitude. Can we have a less thorough, faster-running felix.inp setup as well on master branch for common daily program testing.
Then reserve this input setup for more thorough testing of master branch.

**Comment by RudoRoemer** [comment]
Yes, just suggest a reasonable number (10?) -Rudo

**Comment by JacobJoseph-gu** [comment]
Yeah potentially even lower, 5, if it is for light-hearted quick testing. How would we impliment this in the sample files?
We want one clear FR-GaAs sample folder with correct inputs and detailed outputs for people to download and use immediately. 
It is not essential but I would also find it useful to have a sample folder on master setup for low quality quick testing, such that any developement branch created can immediately do quick test-runs.
