### ISSUE TITLE
Problems compiling felix: master branch

### ISSUE THREAD

**Issue by AJMHubert** [RudoRoemer/Felix#139]
when compiling on the master branch (commit 1f1685c) I get the error message:

  ```
  character(:),allocatable :: initial_msg
                                           1
Error: Deferred-length character component 'initial_msg' at (1) is not yet supported
message_mod.f90:120.43:
```

I use a non-CSC linux (mint) machine, and the GNU compiler not the intel one. My initial guess is the most recent GNU mpi compiler can't deal with 2003 Fortran standard yet, but is only a guess, perhaps I am missing something obvious!

Cheers,

Alex

**Comment by JacobJoseph-gu** [comment]
Pull request #141 should resolve the deferred-length issue. Hopefully there are no other fortran 2003 compatibility issues.

**Comment by AJMHubert** [comment]
Compiled on my Linux machine, works! Still need to test, but looks good. Thank you!

Cheers,

Alex
