### ISSUE TITLE
2003 FORTRAN compatibility?

### ISSUE THREAD

**Issue by JacobJoseph-gu** [RudoRoemer/Felix#150]
I think we should allow FORTRAN 2003 features. How problematic would it be to make sure any server banks or computers we wanted to use had semi-modern compilers?

There is FORTRAN 2008 and 2015, but those new features are unnecessary. 
The following is the international FORTRAN 2003 standards document, which I think is useful:
https://gcc.gnu.org/wiki/GFortranStandards#Fortran_2003

**Comment by RudoRoemer** [comment]
Why? Ie what features that are in f2003 do we need on Felix?

On 12 Aug 2017 12:35 p.m., JacobJoseph-gu <notifications@github.com> wrote:

I think we should allow FORTRAN 2003 features. How problematic would it be to make sure any server banks or computers we wanted to use had semi-modern compilers?

There is FORTRAN 2008 and 2015, but those new features are unnecessary.
The following is the international FORTRAN 2003 standards document, which I think is useful:
https://gcc.gnu.org/wiki/GFortranStandards#Fortran_2003

**Comment by JacobJoseph-gu** [comment]
Valid point, so far I think I've only used one 2003 feature mentioned in #139, which is minor and I will remove.
Let's use FORTRAN 95 standard:
https://gcc.gnu.org/wiki/GFortranStandards#Fortran_95
We should still keep in mind 2003 and 2008 standards, they will likely encourage good habits and future-proof code. 

I will make the changes and lets close this issue
