### ISSUE TITLE
update Felix to read .tif and .dm3 files

### ISSUE THREAD

**Issue by RudoRoemer** [RudoRoemer/Felix#159]
update Felix to read .tif and .dm3 (DigitalMicrograph) files. There are C++ plugins for .tif and a JavaScript for .dm3, they could be useful to convert to Fortran. Also, rejig the input .img and output .bin files into a joint format.

**Comment by JacobJoseph-gu** [comment]
Will track progress by editing this comment:
- ImageJ java website https://imagej.nih.gov/ij/docs/intro.html

**Comment by JacobJoseph-gu** [comment]
61d1270d936f144f75f96d2d54e43d02dcb4c9d9 Added read_dm3_mod.f90 to felix

44d1bb5ec2b63cd0a2fa9b427da7a07dc6f0539a  ReadExperimentalImages() now automatically checks for LR_NxN/ *.img, HR/ *.img, DM3/ *.dm3, *.img, *.dm3
