### ISSUE TITLE
Removing '_mod', changing file and module names

### ISSUE THREAD

**Issue by JacobJoseph-gu** [RudoRoemer/Felix#166]
I began removing '_mod' and realised this is worth discussing briefly first. 

- I suggest having one module per file except for gmodules.f90 / smodules.f90
- I suggest naming files the same as their corresponding module
- Modules can't be named the same as procedures
- read_cif, setup_scattering_factors, contain one key subroutine with the same name. For the module we could use reading_cif, setsup_scatter_factors.
- Do we like the current file/module names, are there some or many we want to rename?
- We could use lower case and underscore for files, modules & procedures and then keep felix classical uppercase style for variables

```
current file names (equal to conatined module name):
alert_mod.f90
bloch_mod.f90
crystallography_mod.f90
felixfunction_mod.f90
felixrefine.f90
gmodules.f90
image.f90
message_mod.f90
read_cif_mod.f90
read_mod.f90
RefineWriteOut.f90
setup_reflections_mod.f90
setup_scattering_factors_mod.f90
simplex.f90
smodules.f90
symmetry.f90
Ug_mod.f90
unused.f90
utilities_mod.f90

We could do something like:

alert_mod.f90                     ---> alert.f90                     contains l_alert()
bloch_mod.f90                     ---> bloch.f90                     contains bloch_coefficient_calculation()
crystallography_mod.f90           ---> crystallography.f90
felixfunction_mod.f90             ---> simulating.f90                contains simulate_and_fit() &
                                                                     felixfunction() & calculate_figure_merit_determine_thickness()
felixrefine.f90                   ---> felixrefine.f90
gmodules.f90                      ---> global_variables.f90
smodules.f90                      ---> global_parameters.f90
image.f90                         ---> image.f90
message_mod.f90                   ---> messaging.f90
read_cif_mod.f90                  ---> reading_cif.f90
read_mod.f90                      ---> reading_files.f90
RefineWriteOut.f90                ---> refine_write_out.f90
setup_reflections_mod.f90         ---> setsup_reflections.f90
setup_scattering_factors_mod.f90  ---> setsup_scatter_factors.f90    contains setup_scatter_factors()
simplex.f90                       ---> simplex.f90
symmetry.f90                      ---> symmetry.f90
Ug_mod.f90                        ---> ug_matrix.f90
unused.f90                        ---> unused.f90
utilities_mod.f90                 ---> utilities.f90
```

**Comment by RudoRoemer** [comment]
Dear all,

“_mod” is apparently the modern naming convention for files containing modules. I was told this as “standard” on a NAG training course in April. Hence I would like to keep them, in fact, rather to make our naming convention consistent with it.

With my best regards,
—
Rudolf A. Roemer
Department of Physics, University of Warwick, Coventry, CV4 7AL, UK www.warwick.ac.uk/go/rudoroemer, +44 7984 353749

**Comment by JacobJoseph-gu** [comment]
I can do that. What do we think about the particular names and lower case & underscore style?

**Comment by rbeanland** [comment]
I think it is a good idea to change some names so that they give better description of the code they contain.     I would rather have the imperative tense in preference to the present continuous tense (e.g. gerunds) in file names, i.e. I would rather have read_cif than reading_cif etc.  The subroutine FelixFunction could be renamed Simulate.  The module felixfunction_mod could be called refinementcontrol_mod or something like that.
I understand that lower case is standard for unix.

**Comment by JacobJoseph-gu** [comment]
3bfab2e0802a835f2ef8578e698b2c8a22c417a6 implemented this
