### ISSUE TITLE
error in FoM&Thickness(NaN Image correlation for pattern  1, thickness   )

### ISSUE THREAD

**Issue by RudoRoemer** [RudoRoemer/Felix#185]
I was trying to run the latest master using the GNU compilers. The code compiles easily but when running in GaAs_short as a test, I am getting the error below. Any ideas what could be happening?
     -----------------------------------------------------------------
     felixrefine: 'Version: master / 1.03 / r.beanland               '
                  'Date: 14-Mar-2019                                 '
                  'Refinements B,C,D,F,H and S working, no HOLZ      '
     -----------------------------------------------------------------
     total number of MPI ranks  001, screen messages via rank 000
     -----------------------------------------------------------------
     Reflection pool of  200 with a minimum of   50 strong beams
     Refining Lattice Parameters, F
     Refining by maximum gradient
     Material: GaAs, F -4 3 m
     77 experimental images successfully loaded
     Mean inner potential  15.32 Volts
     203 unique structure factors
     Starting absorption calculation...
     Absorption    0 hrs   0 mins   6 sec
     Only one independent variable
     Bloch wave calculation...
     Simulation    0 hrs   0 mins  37 sec
  0 = rank, error in FoM&Thickness(NaN Image correlation for pattern  1, thickness   1                                                                                                                                                     )
  0 = rank, error in felixrefine(FigureOfMeritAndThickness)
  0 = rank, error in felixrefine(ABORTING)
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor

**Comment by rbeanland** [comment]
Hi Rudo, my tests on the intel-compiled version on orac and aquarius show no problems.  Which modules are you loading for the GNU-compiled version?  The current Intel modules are:
module load intel/2018.3.222-GCC-7.3.0-2.30  impi/2018.3.222 FFTW/2.1.5 GCC/7.3.0-2.30
I don't know which modules would be equivalent in GNU.

**Comment by RudoRoemer** [comment]
I am testing on non-CSC ubuntu. This is what is needed to get the CircleCI and the general usability of the code going. So there are no module to load, just mpi to install as well as lapack/blas/gfortran. This has of course been done and kept up-to-date.

**Comment by rbeanland** [comment]
Try it in S (simulation-only) mode: IRefineModeFLAG = S in the input file.  This doesn't need to correlate experimental and simulated images so should tell us if the problem is NaN's in the experimental data (it should run) or the simulation (may run and write NaNs in the output file).
Is there a way for me to run it in the same environment as you, so I could try some tests?

**Comment by RudoRoemer** [comment]
Problem persists even with IRefineModeFLAG=S, I am getting

phsht@iMAC-VirtualBox:~/Projects/D-LACBED/Felix/samples/GaAs_short$ ../../src/felix.OPT64NGNU.d 
     -----------------------------------------------------------------
     felixrefine: 'Version: master / 1.03 / r.beanland               '
                  'Date: 14-Mar-2019                                 '
                  'Refinements B,C,D,F,H and S working, no HOLZ      '
     -----------------------------------------------------------------
     total number of MPI ranks  001, screen messages via rank 000
     -----------------------------------------------------------------
     Reflection pool of  200 with a minimum of   50 strong beams
     Material: GaAs, F -4 3 m
     Simulation only
     Mean inner potential  15.32 Volts
     203 unique structure factors
     Starting absorption calculation...
     Absorption    0 hrs   0 mins  24 sec
     Bloch wave calculation...
     Simulation    0 hrs   1 mins   4 sec
     Writing simulations for   1 thicknesses
At line 265 of file write_output_mod.f90 (unit = 49, file = 'GaAs_Sim_0930A_080x080/GaAs_-4-4+10.bin')
Fortran runtime error: Write exceeds length of DIRECT access record

Error termination. Backtrace:
#0  0x7f6f1aa6631a
#1  0x7f6f1aa66ec5
#2  0x7f6f1aa6768d
#3  0x7f6f1abdcae1
#4  0x7f6f1abdcb4d
#5  0x7f6f1abdd624
#6  0x55d924b13bc8
#7  0x55d924ae6499
#8  0x55d924acfe5e
#9  0x7f6f1a0c5b96
#10  0x55d924acfe89
#11  0xffffffffffffffff

**Comment by RudoRoemer** [comment]
The problem was related to missing input files in the samples/ directory. Putting correct input files back has solved the issue.
