### ISSUE TITLE
Message Subroutine

### ISSUE THREAD

**Issue by kidwhizz** [RudoRoemer/Felix#53]
With the iterative method in felixrefine the program will be printing messages for every iteration which will be silly. The fix for this would be to include the ISoftwareFlag in the if loops which contain the print statements. The problem there is that this will make these statements unruly and difficult to read. A better solution will be to create a message subroutine which takes arguments of rank, writeflag, softwareflag and a message and handles the print statement internally

**Comment by AJMHubert** [comment]
Completed
