### ISSUE TITLE
nreflections not equal to Iminreflectionpool

### ISSUE THREAD

**Issue by kidwhizz** [RudoRoemer/Felix#54]
when i implemented the IMinReflectionPool input parameter i put in a check to include any G Vectors with equal magnitudes to the Nth reflection (where N is the number of request reflections), therefore nReflections should always be at least = IMinReflectionPool, however this check seems not to be working and often nreflections < IMinReflectionPool which is bad

**Comment by RudoRoemer** [comment]
superseeded by recent code work, I think. So closing for now.
