### ISSUE TITLE
compiler error in master branch

### ISSUE THREAD

**Issue by RudoRoemer** [RudoRoemer/Felix#65]
aquarius src>make
mpif90 -fbounds-check -fno-range-check -fimplicit-none -fcray-pointer  -DF90 -c gmodules.f90 -I/warwick/mathlib/gnu/x86_64/  -llapack -lblas -lfftw3
mpif90 -fbounds-check -fno-range-check -fimplicit-none -fcray-pointer  -DF90 -c smodules.f90 -I/warwick/mathlib/gnu/x86_64/  -llapack -lblas -lfftw3
smodules.f90:280.31:

        IVariableID,IFelixCount,IPreviousPrintedIteration
                               1
Error: Symbol 'ifelixcount' at (1) already has basic type of INTEGER
make: *** [smodules.o] Error 1

**Comment by RudoRoemer** [comment]
Well, it seems no progress on this up to now. Hence no new release of the code ...

**Comment by kidwhizz** [comment]
all fixed, please check yourself and close the issue
