### ISSUE TITLE
felixsim(   ) error in Deallocation of CAmplitudeandPhase

### ISSUE THREAD

**Issue by RudoRoemer** [RudoRoemer/Felix#68]
IWriteFLAG =2 and IImageFLAG= 012 results in this error message for all cores

felixsim(           1 ) error in Deallocation of CAmplitudeandPhase

**Comment by AJMHubert** [comment]
found the bug, CAmplitudeandPhaseRoot has been deallocated twice, found another one with printing loads of OpenReflectionImage and WriteReflectionImage. fixing both now

**Comment by RudoRoemer** [comment]
In Si sample directory, using the high-res .inp file:

 ReadInpFile( 0 ) INormalDirectionY =          1                         
 Input(): ERR in READ at line          49                                
 # Input file for felixsim/draw version :VERSION: Build :BUILD:

**Comment by AJMHubert** [comment]
Input file has changed (Keith added an InnerConvergenceAngle) fixing

**Comment by AJMHubert** [comment]
should be fixed

**Comment by RudoRoemer** [comment]
In NaBiTi0 sample, I get

ReadCifFile(           0 ) Volume missing!

i.e. this does not yet seem part of the message/error routine.

**Comment by AJMHubert** [comment]
fixed, IAtomnumber indexing information also fixed. It would probably be good to talk about the format for error messaging on Thursday.
