### ISSUE TITLE
ZolzFlag If Statement in bloch.f90

### ISSUE THREAD

**Issue by kidwhizz** [RudoRoemer/Felix#92]
This piece of code in bloch.f90 is stupid

```
  IF (IZolzFLAG.EQ.0) THEN
 CALL EigenSpectrum(nBeams, &
      CUgMatEffective, &
      CEigenValues(:), CEigenVectors(:,:), &
      IErr)
 IF( IErr.NE.0 ) THEN
    PRINT*,"BlochCoefficientCalculation(", my_rank, ") error in EigenSpectrum()"
    RETURN
 ENDIF
 CEigenValues = CEigenValues * RKn/RBigK
 DO knd = 1,nBeams
    CEigenVectors(knd,:) = CEigenVectors(knd,:) / &
         SQRT(1+RGn(IStrongBeamList(knd))/RKn)
 END DO
 ELSE
 CALL EigenSpectrum(nBeams, &
      CUgMatEffective, &
      CEigenValues(:), CEigenVectors(:,:), &
      IErr)
 IF( IErr.NE.0 ) THEN
    PRINT*,"BlochCoefficientCalculation(", my_rank, ") error in EigenSpectrum()"
    RETURN
 ENDIF
 END IF
```

IT should look like this

```
 CALL EigenSpectrum(nBeams, &
      CUgMatEffective, &
      CEigenValues(:), CEigenVectors(:,:), &
      IErr)
 IF( IErr.NE.0 ) THEN
    PRINT*,"BlochCoefficientCalculation(", my_rank, ") error in EigenSpectrum()"
    RETURN
 ENDIF

 IF (IZolzFLAG.EQ.0) THEN
 CEigenValues = CEigenValues * RKn/RBigK
 DO knd = 1,nBeams
    CEigenVectors(knd,:) = CEigenVectors(knd,:) / &
         SQRT(1+RGn(IStrongBeamList(knd))/RKn)
 END DO
 END IF
```

EigenSpectrum is called identically regardless of the value of IZolzFLAG the only difference is what happens to CEigenValues after diagonalisation

**Comment by rbeanland** [comment]
Well yes, I agree the first one is not very nice and the second is more 
efficient.  What is the adjustment applied to the Eigenvalues, 
Eigenvectors, and why? BigK I think I know, but what are Kn, Gn and and 
StrongBeamList?

**Comment by kidwhizz** [comment]
RKn and RGn are the results of k.n and g.n, where k is the incident wave 
vector, g is a reciprocal vector and n is a vector describing the surface 
normal. These only come in when we're dealing with higher order Laue zones 
because maths

Keith

Sent with AquaMail for Android
http://www.aqua-mail.com
